#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 9

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  sym_ident = 2,
  sym_number = 3,
  sym_string = 4,
  sym_char = 5,
  anon_sym__ = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_let = 12,
  anon_sym_EQ = 13,
  anon_sym_return = 14,
  anon_sym_break = 15,
  anon_sym_continue = 16,
  anon_sym_COLON_EQ = 17,
  anon_sym_PLUS_EQ = 18,
  anon_sym_DASH_EQ = 19,
  anon_sym_STAR_EQ = 20,
  anon_sym_SLASH_EQ = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_if = 24,
  anon_sym_else = 25,
  anon_sym_while = 26,
  anon_sym_DASH = 27,
  anon_sym_BANG = 28,
  anon_sym_PLUS = 29,
  anon_sym_STAR = 30,
  anon_sym_SLASH = 31,
  anon_sym_EQ_EQ = 32,
  anon_sym_BANG_EQ = 33,
  anon_sym_GT_EQ = 34,
  anon_sym_LT_EQ = 35,
  sym_source_file = 36,
  sym_block = 37,
  sym_pat = 38,
  sym_pat_tuple = 39,
  sym_pat_array = 40,
  sym_stmt = 41,
  sym_let = 42,
  sym_return = 43,
  sym_break = 44,
  sym_continue = 45,
  sym_set_eq = 46,
  sym_add_eq = 47,
  sym_sub_eq = 48,
  sym_mul_eq = 49,
  sym_div_eq = 50,
  sym_expr = 51,
  sym_if = 52,
  sym_if_else = 53,
  sym_while = 54,
  sym_call = 55,
  sym_tuple = 56,
  sym_unary_op = 57,
  sym_neg = 58,
  sym_not = 59,
  sym_binary_op = 60,
  sym_add = 61,
  sym_sub = 62,
  sym_mul = 63,
  sym_div = 64,
  sym_eq = 65,
  sym_ne = 66,
  sym_ge = 67,
  sym_le = 68,
  aux_sym_block_repeat1 = 69,
  aux_sym_pat_tuple_repeat1 = 70,
  aux_sym_tuple_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [sym_ident] = "ident",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_char] = "char",
  [anon_sym__] = "_",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_pat] = "pat",
  [sym_pat_tuple] = "pat_tuple",
  [sym_pat_array] = "pat_array",
  [sym_stmt] = "stmt",
  [sym_let] = "let",
  [sym_return] = "return",
  [sym_break] = "break",
  [sym_continue] = "continue",
  [sym_set_eq] = "set_eq",
  [sym_add_eq] = "add_eq",
  [sym_sub_eq] = "sub_eq",
  [sym_mul_eq] = "mul_eq",
  [sym_div_eq] = "div_eq",
  [sym_expr] = "expr",
  [sym_if] = "if",
  [sym_if_else] = "if_else",
  [sym_while] = "while",
  [sym_call] = "call",
  [sym_tuple] = "tuple",
  [sym_unary_op] = "unary_op",
  [sym_neg] = "neg",
  [sym_not] = "not",
  [sym_binary_op] = "binary_op",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_ge] = "ge",
  [sym_le] = "le",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_pat_tuple_repeat1] = "pat_tuple_repeat1",
  [aux_sym_tuple_repeat1] = "tuple_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_ident] = sym_ident,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [anon_sym__] = anon_sym__,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_pat] = sym_pat,
  [sym_pat_tuple] = sym_pat_tuple,
  [sym_pat_array] = sym_pat_array,
  [sym_stmt] = sym_stmt,
  [sym_let] = sym_let,
  [sym_return] = sym_return,
  [sym_break] = sym_break,
  [sym_continue] = sym_continue,
  [sym_set_eq] = sym_set_eq,
  [sym_add_eq] = sym_add_eq,
  [sym_sub_eq] = sym_sub_eq,
  [sym_mul_eq] = sym_mul_eq,
  [sym_div_eq] = sym_div_eq,
  [sym_expr] = sym_expr,
  [sym_if] = sym_if,
  [sym_if_else] = sym_if_else,
  [sym_while] = sym_while,
  [sym_call] = sym_call,
  [sym_tuple] = sym_tuple,
  [sym_unary_op] = sym_unary_op,
  [sym_neg] = sym_neg,
  [sym_not] = sym_not,
  [sym_binary_op] = sym_binary_op,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_ge] = sym_ge,
  [sym_le] = sym_le,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_pat_tuple_repeat1] = aux_sym_pat_tuple_repeat1,
  [aux_sym_tuple_repeat1] = aux_sym_tuple_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pat] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_array] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_break] = {
    .visible = true,
    .named = true,
  },
  [sym_continue] = {
    .visible = true,
    .named = true,
  },
  [sym_set_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_add_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_sub_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_mul_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_div_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_if_else] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pat_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_body_else = 3,
  field_body_if = 4,
  field_cond = 5,
  field_continue = 6,
  field_expr = 7,
  field_func = 8,
  field_lhs = 9,
  field_pat = 10,
  field_rhs = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_body_else] = "body_else",
  [field_body_if] = "body_if",
  [field_cond] = "cond",
  [field_continue] = "continue",
  [field_expr] = "expr",
  [field_func] = "func",
  [field_lhs] = "lhs",
  [field_pat] = "pat",
  [field_rhs] = "rhs",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_continue, 0},
  [1] =
    {field_expr, 1},
  [2] =
    {field_expr, 2},
    {field_pat, 0},
  [4] =
    {field_lhs, 0},
    {field_rhs, 2},
  [6] =
    {field_args, 2},
    {field_func, 0},
  [8] =
    {field_expr, 3},
    {field_pat, 1},
  [10] =
    {field_body, 4},
    {field_cond, 2},
  [12] =
    {field_body_else, 6},
    {field_body_if, 4},
    {field_cond, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '!', 104,
        '"', 2,
        '\'', 3,
        '(', 74,
        ')', 76,
        '*', 106,
        '+', 105,
        ',', 75,
        '-', 102,
        '/', 107,
        ':', 9,
        ';', 44,
        '<', 10,
        '=', 82,
        '>', 12,
        '[', 77,
        ']', 78,
        '_', 72,
        'b', 31,
        'c', 30,
        'e', 25,
        'i', 20,
        'l', 14,
        'r', 19,
        'w', 21,
        '{', 94,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(103);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '-') ADVANCE(101);
      if (lookahead == 'i') ADVANCE(51);
      if (lookahead == 'w') ADVANCE(52);
      if (lookahead == '{') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '\\') ADVANCE(39);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(74);
      if (lookahead == '[') ADVANCE(77);
      if (lookahead == '_') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(109);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(93);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(89);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(108);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(110);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(96);
      END_STATE();
    case 21:
      if (lookahead == 'h') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'k') ADVANCE(85);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(79);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 39:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 41:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '!', 103,
        '"', 2,
        '\'', 3,
        '(', 74,
        ')', 76,
        '*', 6,
        '+', 7,
        ',', 75,
        '-', 102,
        '/', 8,
        ':', 9,
        '=', 81,
        '[', 77,
        ']', 78,
        '_', 73,
        'b', 61,
        'c', 60,
        'i', 51,
        'l', 46,
        'r', 50,
        'w', 52,
        '{', 94,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 42:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '!', 5,
        '(', 74,
        ')', 76,
        '*', 106,
        '+', 105,
        ',', 75,
        '-', 102,
        '/', 107,
        ':', 9,
        ';', 44,
        '<', 10,
        '=', 11,
        '>', 12,
        'e', 25,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'h') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'k') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym__);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(108);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_break);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_continue);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(91);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(109);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '=') ADVANCE(93);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 41},
  [2] = {.lex_state = 41},
  [3] = {.lex_state = 41},
  [4] = {.lex_state = 41},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 41},
  [32] = {.lex_state = 41},
  [33] = {.lex_state = 42},
  [34] = {.lex_state = 41},
  [35] = {.lex_state = 42},
  [36] = {.lex_state = 42},
  [37] = {.lex_state = 42},
  [38] = {.lex_state = 42},
  [39] = {.lex_state = 42},
  [40] = {.lex_state = 42},
  [41] = {.lex_state = 42},
  [42] = {.lex_state = 42},
  [43] = {.lex_state = 42},
  [44] = {.lex_state = 42},
  [45] = {.lex_state = 42},
  [46] = {.lex_state = 42},
  [47] = {.lex_state = 42},
  [48] = {.lex_state = 42},
  [49] = {.lex_state = 42},
  [50] = {.lex_state = 42},
  [51] = {.lex_state = 42},
  [52] = {.lex_state = 42},
  [53] = {.lex_state = 42},
  [54] = {.lex_state = 42},
  [55] = {.lex_state = 42},
  [56] = {.lex_state = 42},
  [57] = {.lex_state = 42},
  [58] = {.lex_state = 42},
  [59] = {.lex_state = 42},
  [60] = {.lex_state = 42},
  [61] = {.lex_state = 42},
  [62] = {.lex_state = 42},
  [63] = {.lex_state = 42},
  [64] = {.lex_state = 42},
  [65] = {.lex_state = 42},
  [66] = {.lex_state = 42},
  [67] = {.lex_state = 42},
  [68] = {.lex_state = 41},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 41},
  [71] = {.lex_state = 41},
  [72] = {.lex_state = 41},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 41},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(90),
    [sym_block] = STATE(89),
    [sym_pat] = STATE(79),
    [sym_pat_tuple] = STATE(68),
    [sym_pat_array] = STATE(68),
    [sym_stmt] = STATE(85),
    [sym_let] = STATE(88),
    [sym_return] = STATE(88),
    [sym_break] = STATE(88),
    [sym_continue] = STATE(88),
    [sym_set_eq] = STATE(88),
    [sym_add_eq] = STATE(88),
    [sym_sub_eq] = STATE(88),
    [sym_mul_eq] = STATE(88),
    [sym_div_eq] = STATE(88),
    [sym_expr] = STATE(56),
    [sym_if] = STATE(53),
    [sym_if_else] = STATE(53),
    [sym_while] = STATE(53),
    [sym_call] = STATE(53),
    [sym_tuple] = STATE(53),
    [sym_unary_op] = STATE(53),
    [sym_neg] = STATE(42),
    [sym_not] = STATE(42),
    [sym_binary_op] = STATE(53),
    [sym_add] = STATE(41),
    [sym_sub] = STATE(41),
    [sym_mul] = STATE(41),
    [sym_div] = STATE(41),
    [sym_eq] = STATE(41),
    [sym_ne] = STATE(41),
    [sym_ge] = STATE(41),
    [sym_le] = STATE(41),
    [aux_sym_block_repeat1] = STATE(3),
    [aux_sym_tuple_repeat1] = STATE(25),
    [sym_ident] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [sym_char] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(15),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
  },
  [2] = {
    [sym_block] = STATE(86),
    [sym_pat] = STATE(79),
    [sym_pat_tuple] = STATE(68),
    [sym_pat_array] = STATE(68),
    [sym_stmt] = STATE(85),
    [sym_let] = STATE(88),
    [sym_return] = STATE(88),
    [sym_break] = STATE(88),
    [sym_continue] = STATE(88),
    [sym_set_eq] = STATE(88),
    [sym_add_eq] = STATE(88),
    [sym_sub_eq] = STATE(88),
    [sym_mul_eq] = STATE(88),
    [sym_div_eq] = STATE(88),
    [sym_expr] = STATE(56),
    [sym_if] = STATE(53),
    [sym_if_else] = STATE(53),
    [sym_while] = STATE(53),
    [sym_call] = STATE(53),
    [sym_tuple] = STATE(53),
    [sym_unary_op] = STATE(53),
    [sym_neg] = STATE(42),
    [sym_not] = STATE(42),
    [sym_binary_op] = STATE(53),
    [sym_add] = STATE(41),
    [sym_sub] = STATE(41),
    [sym_mul] = STATE(41),
    [sym_div] = STATE(41),
    [sym_eq] = STATE(41),
    [sym_ne] = STATE(41),
    [sym_ge] = STATE(41),
    [sym_le] = STATE(41),
    [aux_sym_block_repeat1] = STATE(3),
    [aux_sym_tuple_repeat1] = STATE(25),
    [sym_ident] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [sym_char] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(15),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
  },
  [3] = {
    [sym_pat] = STATE(79),
    [sym_pat_tuple] = STATE(68),
    [sym_pat_array] = STATE(68),
    [sym_stmt] = STATE(87),
    [sym_let] = STATE(88),
    [sym_return] = STATE(88),
    [sym_break] = STATE(88),
    [sym_continue] = STATE(88),
    [sym_set_eq] = STATE(88),
    [sym_add_eq] = STATE(88),
    [sym_sub_eq] = STATE(88),
    [sym_mul_eq] = STATE(88),
    [sym_div_eq] = STATE(88),
    [sym_expr] = STATE(55),
    [sym_if] = STATE(53),
    [sym_if_else] = STATE(53),
    [sym_while] = STATE(53),
    [sym_call] = STATE(53),
    [sym_tuple] = STATE(53),
    [sym_unary_op] = STATE(53),
    [sym_neg] = STATE(42),
    [sym_not] = STATE(42),
    [sym_binary_op] = STATE(53),
    [sym_add] = STATE(41),
    [sym_sub] = STATE(41),
    [sym_mul] = STATE(41),
    [sym_div] = STATE(41),
    [sym_eq] = STATE(41),
    [sym_ne] = STATE(41),
    [sym_ge] = STATE(41),
    [sym_le] = STATE(41),
    [aux_sym_block_repeat1] = STATE(4),
    [aux_sym_tuple_repeat1] = STATE(25),
    [sym_ident] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [sym_char] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_return] = ACTIONS(15),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      anon_sym_let,
    ACTIONS(45), 1,
      anon_sym_return,
    ACTIONS(48), 1,
      anon_sym_break,
    ACTIONS(51), 1,
      anon_sym_continue,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(79), 1,
      sym_pat,
    STATE(84), 1,
      sym_stmt,
    ACTIONS(31), 2,
      sym_ident,
      anon_sym__,
    ACTIONS(54), 2,
      anon_sym_if,
      anon_sym_while,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
    ACTIONS(34), 6,
      sym_number,
      sym_string,
      sym_char,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(88), 9,
      sym_let,
      sym_return,
      sym_break,
      sym_continue,
      sym_set_eq,
      sym_add_eq,
      sym_sub_eq,
      sym_mul_eq,
      sym_div_eq,
  [59] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(46), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [112] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(51), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [165] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(59), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [218] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(45), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [271] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(9), 1,
      aux_sym_tuple_repeat1,
    STATE(52), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [324] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(61), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [377] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(57), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [430] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(44), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [483] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(40), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [536] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(37), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [589] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(38), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [642] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(47), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [695] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(54), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [748] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(39), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [801] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(49), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [854] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(50), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [907] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(58), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [960] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(67), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1013] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(66), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1066] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(65), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1119] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(9), 1,
      aux_sym_tuple_repeat1,
    STATE(52), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1172] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(60), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1225] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(64), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1278] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(63), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1331] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(62), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1384] = 12,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(56), 1,
      sym_ident,
    STATE(25), 1,
      aux_sym_tuple_repeat1,
    STATE(48), 1,
      sym_expr,
    STATE(42), 2,
      sym_neg,
      sym_not,
    ACTIONS(5), 3,
      sym_number,
      sym_string,
      sym_char,
    STATE(53), 7,
      sym_if,
      sym_if_else,
      sym_while,
      sym_call,
      sym_tuple,
      sym_unary_op,
      sym_binary_op,
    STATE(41), 8,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_ge,
      sym_le,
  [1437] = 3,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(34), 8,
      sym_number,
      sym_string,
      sym_char,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(54), 8,
      sym_ident,
      anon_sym__,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_if,
      anon_sym_while,
  [1462] = 3,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(34), 8,
      sym_number,
      sym_string,
      sym_char,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(54), 8,
      sym_ident,
      anon_sym__,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_if,
      anon_sym_while,
  [1487] = 4,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(66), 5,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1513] = 2,
    ACTIONS(34), 8,
      sym_number,
      sym_string,
      sym_char,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(54), 8,
      sym_ident,
      anon_sym__,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_if,
      anon_sym_while,
  [1534] = 2,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1554] = 1,
    ACTIONS(70), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1571] = 9,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
  [1604] = 1,
    ACTIONS(90), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1621] = 1,
    ACTIONS(92), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1638] = 5,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1663] = 1,
    ACTIONS(96), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1680] = 1,
    ACTIONS(98), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1697] = 1,
    ACTIONS(100), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1714] = 5,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(102), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1739] = 9,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(104), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
  [1772] = 3,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(106), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1793] = 5,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(108), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1818] = 1,
    ACTIONS(110), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1835] = 1,
    ACTIONS(112), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1852] = 3,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(114), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1873] = 5,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1898] = 1,
    ACTIONS(118), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1915] = 1,
    ACTIONS(62), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1932] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(122), 1,
      anon_sym_else,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1967] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1999] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2031] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_SEMI,
  [2062] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(130), 1,
      anon_sym_SEMI,
  [2093] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_SEMI,
  [2124] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
  [2155] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_SEMI,
  [2186] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
  [2217] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
  [2248] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_SEMI,
  [2279] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_SEMI,
  [2310] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_SEMI,
  [2341] = 10,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_PLUS,
    ACTIONS(78), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(82), 1,
      anon_sym_EQ_EQ,
    ACTIONS(84), 1,
      anon_sym_BANG_EQ,
    ACTIONS(86), 1,
      anon_sym_GT_EQ,
    ACTIONS(88), 1,
      anon_sym_LT_EQ,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_SEMI,
  [2372] = 1,
    ACTIONS(66), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [2384] = 2,
    ACTIONS(150), 3,
      sym_ident,
      anon_sym_if,
      anon_sym_while,
    ACTIONS(152), 6,
      sym_number,
      sym_string,
      sym_char,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
  [2398] = 1,
    ACTIONS(154), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [2410] = 1,
    ACTIONS(156), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [2422] = 1,
    ACTIONS(158), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
  [2434] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(77), 1,
      aux_sym_pat_tuple_repeat1,
    STATE(94), 1,
      sym_pat,
    ACTIONS(7), 2,
      sym_ident,
      anon_sym__,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
  [2455] = 6,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_LBRACK,
    STATE(74), 1,
      aux_sym_pat_tuple_repeat1,
    STATE(94), 1,
      sym_pat,
    ACTIONS(160), 2,
      sym_ident,
      anon_sym__,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
  [2476] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(76), 1,
      aux_sym_pat_tuple_repeat1,
    STATE(82), 1,
      sym_pat,
    ACTIONS(7), 2,
      sym_ident,
      anon_sym__,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
  [2497] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(74), 1,
      aux_sym_pat_tuple_repeat1,
    STATE(83), 1,
      sym_pat,
    ACTIONS(7), 2,
      sym_ident,
      anon_sym__,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
  [2518] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(74), 1,
      aux_sym_pat_tuple_repeat1,
    STATE(81), 1,
      sym_pat,
    ACTIONS(7), 2,
      sym_ident,
      anon_sym__,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
  [2539] = 5,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(95), 1,
      sym_pat,
    ACTIONS(7), 2,
      sym_ident,
      anon_sym__,
    STATE(68), 2,
      sym_pat_tuple,
      sym_pat_array,
  [2557] = 5,
    ACTIONS(169), 1,
      anon_sym_COLON_EQ,
    ACTIONS(171), 1,
      anon_sym_PLUS_EQ,
    ACTIONS(173), 1,
      anon_sym_DASH_EQ,
    ACTIONS(175), 1,
      anon_sym_STAR_EQ,
    ACTIONS(177), 1,
      anon_sym_SLASH_EQ,
  [2573] = 2,
    ACTIONS(179), 2,
      sym_ident,
      anon_sym__,
    ACTIONS(181), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [2582] = 2,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
  [2589] = 2,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
  [2596] = 2,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
  [2603] = 1,
    ACTIONS(191), 1,
      anon_sym_SEMI,
  [2607] = 1,
    ACTIONS(193), 1,
      anon_sym_SEMI,
  [2611] = 1,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
  [2615] = 1,
    ACTIONS(197), 1,
      anon_sym_SEMI,
  [2619] = 1,
    ACTIONS(199), 1,
      anon_sym_SEMI,
  [2623] = 1,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [2627] = 1,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
  [2631] = 1,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
  [2635] = 1,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
  [2639] = 1,
    ACTIONS(209), 1,
      anon_sym_SEMI,
  [2643] = 1,
    ACTIONS(183), 1,
      anon_sym_COMMA,
  [2647] = 1,
    ACTIONS(211), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 59,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 165,
  [SMALL_STATE(8)] = 218,
  [SMALL_STATE(9)] = 271,
  [SMALL_STATE(10)] = 324,
  [SMALL_STATE(11)] = 377,
  [SMALL_STATE(12)] = 430,
  [SMALL_STATE(13)] = 483,
  [SMALL_STATE(14)] = 536,
  [SMALL_STATE(15)] = 589,
  [SMALL_STATE(16)] = 642,
  [SMALL_STATE(17)] = 695,
  [SMALL_STATE(18)] = 748,
  [SMALL_STATE(19)] = 801,
  [SMALL_STATE(20)] = 854,
  [SMALL_STATE(21)] = 907,
  [SMALL_STATE(22)] = 960,
  [SMALL_STATE(23)] = 1013,
  [SMALL_STATE(24)] = 1066,
  [SMALL_STATE(25)] = 1119,
  [SMALL_STATE(26)] = 1172,
  [SMALL_STATE(27)] = 1225,
  [SMALL_STATE(28)] = 1278,
  [SMALL_STATE(29)] = 1331,
  [SMALL_STATE(30)] = 1384,
  [SMALL_STATE(31)] = 1437,
  [SMALL_STATE(32)] = 1462,
  [SMALL_STATE(33)] = 1487,
  [SMALL_STATE(34)] = 1513,
  [SMALL_STATE(35)] = 1534,
  [SMALL_STATE(36)] = 1554,
  [SMALL_STATE(37)] = 1571,
  [SMALL_STATE(38)] = 1604,
  [SMALL_STATE(39)] = 1621,
  [SMALL_STATE(40)] = 1638,
  [SMALL_STATE(41)] = 1663,
  [SMALL_STATE(42)] = 1680,
  [SMALL_STATE(43)] = 1697,
  [SMALL_STATE(44)] = 1714,
  [SMALL_STATE(45)] = 1739,
  [SMALL_STATE(46)] = 1772,
  [SMALL_STATE(47)] = 1793,
  [SMALL_STATE(48)] = 1818,
  [SMALL_STATE(49)] = 1835,
  [SMALL_STATE(50)] = 1852,
  [SMALL_STATE(51)] = 1873,
  [SMALL_STATE(52)] = 1898,
  [SMALL_STATE(53)] = 1915,
  [SMALL_STATE(54)] = 1932,
  [SMALL_STATE(55)] = 1967,
  [SMALL_STATE(56)] = 1999,
  [SMALL_STATE(57)] = 2031,
  [SMALL_STATE(58)] = 2062,
  [SMALL_STATE(59)] = 2093,
  [SMALL_STATE(60)] = 2124,
  [SMALL_STATE(61)] = 2155,
  [SMALL_STATE(62)] = 2186,
  [SMALL_STATE(63)] = 2217,
  [SMALL_STATE(64)] = 2248,
  [SMALL_STATE(65)] = 2279,
  [SMALL_STATE(66)] = 2310,
  [SMALL_STATE(67)] = 2341,
  [SMALL_STATE(68)] = 2372,
  [SMALL_STATE(69)] = 2384,
  [SMALL_STATE(70)] = 2398,
  [SMALL_STATE(71)] = 2410,
  [SMALL_STATE(72)] = 2422,
  [SMALL_STATE(73)] = 2434,
  [SMALL_STATE(74)] = 2455,
  [SMALL_STATE(75)] = 2476,
  [SMALL_STATE(76)] = 2497,
  [SMALL_STATE(77)] = 2518,
  [SMALL_STATE(78)] = 2539,
  [SMALL_STATE(79)] = 2557,
  [SMALL_STATE(80)] = 2573,
  [SMALL_STATE(81)] = 2582,
  [SMALL_STATE(82)] = 2589,
  [SMALL_STATE(83)] = 2596,
  [SMALL_STATE(84)] = 2603,
  [SMALL_STATE(85)] = 2607,
  [SMALL_STATE(86)] = 2611,
  [SMALL_STATE(87)] = 2615,
  [SMALL_STATE(88)] = 2619,
  [SMALL_STATE(89)] = 2623,
  [SMALL_STATE(90)] = 2627,
  [SMALL_STATE(91)] = 2631,
  [SMALL_STATE(92)] = 2635,
  [SMALL_STATE(93)] = 2639,
  [SMALL_STATE(94)] = 2643,
  [SMALL_STATE(95)] = 2647,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pat, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 5),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 5, 0, 7),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_neg, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ge, 3, 0, 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_le, 3, 0, 4),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_else, 7, 0, 8),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eq, 3, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ne, 3, 0, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 5, 0, 7),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_break, 2, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div_eq, 3, 0, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 4, 0, 6),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_eq, 3, 0, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_eq, 3, 0, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_eq, 3, 0, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_eq, 3, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pat_array, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pat_array, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pat_tuple, 4, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pat_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pat_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pat_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pat_tuple_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pat_tuple_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continue, 1, 0, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_QS(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
